# Generated by Django 3.1.2 on 2020-10-21 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('street', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=20, null=True)),
                ('company_name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Default Dealership', max_length=50)),
                ('phone', models.CharField(default='123-456-7891', max_length=50)),
                ('city', models.CharField(default='Default City', max_length=50)),
                ('state', models.CharField(default='Default State', max_length=50)),
                ('website', models.CharField(max_length=1000, null=True)),
                ('tax_id', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dealership',
                'verbose_name_plural': 'Dealerships',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, null=True)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnivalapi.dealership')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Employee Type',
                'verbose_name_plural': 'Employee Types',
            },
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Repair Type',
                'verbose_name_plural': 'Repair Types',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Purchase', max_length=8)),
            ],
            options={
                'verbose_name': 'Sales Type',
                'verbose_name_plural': 'Sales Types',
            },
        ),
        migrations.CreateModel(
            name='VehicleBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Body Type',
                'verbose_name_plural': 'Vehicle Body Types',
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Make',
                'verbose_name_plural': 'Vehicle Makes',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='Default Model Name', max_length=20)),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=20, null=True)),
                ('make', models.CharField(max_length=20, null=True)),
                ('model', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(default='AAAAAAAAAAAAAAA', max_length=50)),
                ('engine_type', models.CharField(default='V6', max_length=2)),
                ('exterior_color', models.CharField(default='Default Exterior Color', max_length=50)),
                ('interior_color', models.CharField(default='Default Interior Color', max_length=50)),
                ('floor_price', models.IntegerField(default=20000)),
                ('msr_price', models.IntegerField(default=15000)),
                ('miles_count', models.IntegerField(default=100)),
                ('year_of_car', models.IntegerField(default=2020)),
                ('is_sold', models.BooleanField(default=False)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicletype', to='carnivalapi.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1000, max_digits=8)),
                ('deposit', models.IntegerField(default=1000)),
                ('purchase_date', models.DateField(default='2000-01-01')),
                ('pickup_date', models.DateField(default='2000-01-01')),
                ('invoice_number', models.CharField(default='1111111111', max_length=50)),
                ('payment_method', models.CharField(default='visa', max_length=50)),
                ('returned', models.BooleanField(default='false')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='carnivalapi.customer')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership', to='carnivalapi.dealership')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='carnivalapi.employee')),
                ('sales_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saletype', to='carnivalapi.saletype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='carnivalapi.vehicle')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='OilChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_change_date', models.DateField(default='2000-01-01')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleoilchange', to='carnivalapi.vehicle')),
            ],
            options={
                'verbose_name': 'Oil Change',
                'verbose_name_plural': 'Oil Changes',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnivalapi.employeetype'),
        ),
        migrations.CreateModel(
            name='DealershipEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedealership', to='carnivalapi.dealership')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealershipemployee', to='carnivalapi.employee')),
            ],
            options={
                'verbose_name': 'Dealership Employee',
                'verbose_name_plural': 'Dealership Employees',
            },
        ),
        migrations.CreateModel(
            name='CarRepairType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date_occured', models.DateTimeField(auto_now=True)),
                ('repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairtype', to='carnivalapi.repairtype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiclerepair', to='carnivalapi.vehicle')),
            ],
            options={
                'verbose_name': 'Car Repair Type',
                'verbose_name_plural': 'Car Repair Types',
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('date_received', models.DateField(null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='carnivalapi.sale')),
            ],
            options={
                'verbose_name': 'Account Receivable',
                'verbose_name_plural': 'Accounts Receivable',
            },
        ),
    ]
