# Generated by Django 3.1.2 on 2020-10-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnivalapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='isActive',
        ),
        migrations.AddField(
            model_name='employee',
            name='dealership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carnivalapi.dealership'),
            preserve_default=False,
        ),
    ]
