# Generated by Django 3.1.2 on 2020-10-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnivalapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='returned',
        ),
    ]
