# Generated by Django 3.1.2 on 2020-10-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnivalapi', '0002_remove_sale_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='returned',
            field=models.BooleanField(null=True),
        ),
    ]
