# Generated by Django 3.1.2 on 2020-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnivalapi', '0003_sale_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
