from .customer import Customers
from .dealership import Dealerships
from .sale import Sales
from .account_receivable import AccountsReceivable
from .carrepairtype import CarRepairTypes
from .dealershipemployee import DealershipEmployees
from .employee import Employees
from .employeetype import EmployeeTypes
from .repairtype import RepairType
from .oilchangelog import OilChangeLog
from .vehiclebodytype import VehicleBodyType
from .vehicletype import VehicleType