from .customer import Customers
from .dealership import Dealerships
from .sale import Sales
from .account_receivable import AccountsReceivable
from .carrepairtype import CarRepairTypes
from .dealershipemployee import DealershipEmployees
from .employee import Employees
from .employeetype import EmployeeTypes
from .repairtype import RepairTypes
from .oilchangelog import OilChangeLogs
from .vehiclebodytype import VehicleBodyTypes
from .vehicletype import VehicleTypes
from .saletype import SaleTypes
from .vehicle import Vehicles
from .vehiclemake import VehicleMakes